### PR TITLE
Django >= 1.9 support

### PR DESCRIPTION
**Pull request by thijstriemstra**
This fixes a syntax error in the tests that allows you to run them when using python 3 (tested with 3.3).
Also adds a changelog for 0.3.2. Hopefuly 0.3.3 entry lists python 3 support :)

See #23.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Also added Django 1.9 support.

**Comment by thijstriemstra** [comment]
@zmathew ping

**Comment by zmathew** [comment]
@thijstriemstra I clearly an unable to maintain this project anymore, happy to point to your fork if you wish?

**Comment by thijstriemstra** [comment]
@zmathew I would be interested in being a contributor, perhaps you can add me to this project (and add user 'thape' to access the pypi repo).

**Comment by zmathew** [comment]
@thijstriemstra pypi says "User does not exist" when trying to add `thape` as the username

**Comment by thijstriemstra** [comment]
Shit sorry, it's `collab`.

**Comment by zmathew** [comment]
done!

**Pull request merged**
